### PR TITLE
Create trie.cpp

### PR DESCRIPTION
**Pull request by sandesh-3112**
trie data structure successfully added...please merge this PR request under hacktoberfest tag

### CODE REVIEW

**Comment by sandesh-3112** [comment]
could you please tell me what wrong in this code why this piece of code in not mergeable

**Comment by hogrider301** [comment]
> could you please tell me what wrong in this code why this piece of code in not mergeable

The code is right. but I just asked you to make a folder trie and then put this file there.

**Comment by sandesh-3112** [comment]
can you please make the trie folder i dont know how to make a folder on github

**Comment by hogrider301** [comment]
> 

Dude , you are directly uploading the file. that's why you are confused abt folder and all..
Better fork , clone and make folder and put file there and push it.Make pull request.

**Comment by hogrider301** [comment]
> can you please make the trie folder i dont know how to make a folder on github

Keep the file name as "Trie/trie.cpp"

**Pull request closed without merging**
